/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as marketingIndexRouteImport } from './routes/(marketing)/index'
import { Route as marketingAboutIndexRouteImport } from './routes/(marketing)/about/index'

const marketingIndexRoute = marketingIndexRouteImport.update({
  id: '/(marketing)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingAboutIndexRoute = marketingAboutIndexRouteImport.update({
  id: '/(marketing)/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof marketingIndexRoute
  '/about/': typeof marketingAboutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof marketingIndexRoute
  '/about': typeof marketingAboutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(marketing)/': typeof marketingIndexRoute
  '/(marketing)/about/': typeof marketingAboutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about'
  id: '__root__' | '/(marketing)/' | '/(marketing)/about/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  marketingIndexRoute: typeof marketingIndexRoute
  marketingAboutIndexRoute: typeof marketingAboutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(marketing)/': {
      id: '/(marketing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/about/': {
      id: '/(marketing)/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof marketingAboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  marketingIndexRoute: marketingIndexRoute,
  marketingAboutIndexRoute: marketingAboutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
